
version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:

  rspec-test:
    resource_class: small
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run RSpec Tests
          command: bundle exec rspec

  rubocop:
    resource_class: small
    docker:
      - image: cimg/ruby:3.4
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --parallel

  release:
    resource_class: small
    parameters:
      tag:
        type: string
    docker:
      - image: cimg/ruby:3.4
    environment:
      RELEASE_TAG: << parameters.tag >>
    steps:
      - checkout
      - run:
          name: Set up credentials
          command: |
            mkdir -p $HOME/.gem
            touch $HOME/.gem/credentials
            chmod 0600 $HOME/.gem/credentials
            echo -e "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
      - run:
          name: Set version
          command: |
            sed -i "s/'0\.0\.0'/'${RELEASE_TAG}'/" lib/queue_datadog_monitor/version.rb
            grep -qF "'${RELEASE_TAG}'" lib/queue_datadog_monitor/version.rb
      - run:
          name: Build gem
          command: gem build *.gemspec
      - run:
          name: Push gem
          command: gem push --KEY github --host https://rubygems.pkg.github.com/matic-insurance *.gem

workflows:

  queue-datadog-monitor.build-pull-request:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:

      - rspec-test:
          name: rspec
          matrix:
            parameters:
              ruby-version: [ '3.4' ]

      - rubocop:
          name: rubocop

  queue-datadog-monitor.build-main:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:

      - rspec-test:
          name: rspec
          matrix:
            parameters:
              ruby-version: [ '3.4' ]

      - rubocop:
          name: rubocop

  queue-datadog-monitor.release:
    jobs:

      - release:
          context: gem-publishing
          tag: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
